#!/bin/bash

export SRCFILE="bats"
export SRCDIR="src/"
export OUTDIR="out/"



# Generate README.md from source in Galician

export LANGOPT="_gl"

pandoc --from markdown --to markdown_github --output=../README.md $SRCDIR$SRCFILE$LANGOPT.md

# Generate docs for galician language
# - Mediawiki
# - PDF
# - LaTeX
# - pandoc from pandoc (for test purposes)
pandoc --from markdown --to mediawiki --output=$OUTDIR$SRCFILE$LANGOPT.mw  $SRCDIR$SRCFILE$LANGOPT.md
pandoc --smart --standalone --from markdown --to latex --latex-engine=xelatex --output=$OUTDIR$SRCFILE$LANGOPT.pdf  $SRCDIR$SRCFILE$LANGOPT.md
pandoc --smart --from markdown --to latex --output=$OUTDIR$SRCFILE$LANGOPT.tex  $SRCDIR$SRCFILE$LANGOPT.md
pandoc --from markdown --to markdown --output="$OUTDIR""test.md"  $SRCDIR$SRCFILE$LANGOPT.md
